#@ load("@ytt:data", "data")

#@ def labels():
app: #@ data.values.name
#@ end

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: #@ labels()
  name: #@ data.values.name
  namespace: #@ data.values.namespace
spec:
  replicas: 1
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      labels: #@ labels()
    spec:
      containers:
      - image: gcr.io/cf-identity-service-oak/mbrauer/pod-terminated-tls
        name: #@ data.values.name
#!        env:
#!          - name: SERVER_PORT
#!            value: 8443
#!          - name: SERVER_SSL_ENABLED
#!            value: true
#!          - name: SERVER_PORT
#!            value: 8443
---
apiVersion: v1
kind: Service
metadata:
  labels: #@ labels()
  name: #@ data.values.name
  namespace: #@ data.values.namespace
spec:
  selector: #@ labels()
  ports:
  - port: 80
    targetPort: 8443
